<a href="https://colab.research.google.com/github/fannyfagame-spec/NoteBook-Jupiter/blob/main/%5BJupyter_Notebooks_Youth%5D_Pandas_Dataframe_%204.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<font size="+3">Module 33 - Pandas Dataframe</font>

In this notebook, we are going to discuss how to:
- Create a DataFrame
- Reading a Data file(.csv)
- Attributes of Data Frame-head(), tail(), T(),dtype(), ndim(), shape()
- DataFrame Indexing
- Missing Value treatment-isnull(), notnull()

## Create a DataFrame

In [55]:
#Import pandas Library
import pandas as pd

In [56]:
# Create a Data frame
# initialize list elements
data = [10,20,30,40,50,60]

In [57]:
# Create the pandas DataFrame with column name is provided explicitly
df = pd.DataFrame(data, columns=['Numbers'])
df

   Numbers
0       10
1       20
2       30
3       40
4       50
5       60

**<p style="font-family: Arial; font-size:1.4em;color:blue;">Exercise: Create DataFrame </p>**

In [58]:
## Create a dataframe with details of marks of  5 students

In [59]:
import pandas as pd

kids_data = {
    'Kids No.': range(1, 11),
    'Name': ['Alice','Bob','Charlie','Diana','Eve','Frank','Grace','Hank','Ivy','Jack'],
    'Bag Color': ['Red','Blue','Green','Yellow','Pink','Orange','Purple','White','Black','Brown'],
    'Items in Bag': ['Book','Pencil','Ruler','Eraser','Crayon','Notebook','Pen','Scissors','Glue','Marker']
}

df_kids = pd.DataFrame(kids_data)
df_kids.to_csv('Datasets/KidsData.csv', index=False)
print("File created!")

File created!

## Reading a file (.csv)

In [60]:
# Reading a data file(.csv)
# Let us load a .csv file with name:Students Marks.csv
## Check the file path,whether it is in the same path as notebook
## reading the csv file
Studentsdataframe=pd.read_csv("Datasets/Students Marks.csv")

In [61]:
## Printing the Dataset as a dataframe
Studentsdataframe

   S.No Student Name  Roll No.  Total Marks
0     1        Annie    100231           60
1     2          Amy    100232           65
2     3          Ali    100233           70
3     4       Daniel    100234           56
4     5       Donald    100235           45
5     6       Dinesh    100236           85
6     7        Jacob    100237           75
7     8        Julie    100238           85
8     9      Sandhya    100239           60
9    10        Salim    100240           70

**<p style="font-family: Arial; font-size:1.4em;color:blue;">Exercise: Reading a file </p>**

In [62]:
# Attached in this module is a dataset about kids going to school with different items in each of the coloured bag.Download the file
# and print the dataframe.

In [63]:
data = {
    'Name': ['Alice','Bob','Charlie','Diana','Eve'],
    'Marks': [85, 90, 78, 92, 88]
}
df = pd.DataFrame(data)
df

      Name  Marks
0    Alice     85
1      Bob     90
2  Charlie     78
3    Diana     92
4      Eve     88

## Attributes of DataFrame

### Attributes-head()

In [64]:
#  head function to read a data file
Studentsdataframe.head()

   S.No Student Name  Roll No.  Total Marks
0     1        Annie    100231           60
1     2          Amy    100232           65
2     3          Ali    100233           70
3     4       Daniel    100234           56
4     5       Donald    100235           45

### Attributes-tail()

In [65]:
# tail  function to read a data file
Studentsdataframe.tail()

   S.No Student Name  Roll No.  Total Marks
5     6       Dinesh    100236           85
6     7        Jacob    100237           75
7     8        Julie    100238           85
8     9      Sandhya    100239           60
9    10        Salim    100240           70

### Attributes-Transpose()

In [66]:
# Transpose of the data frame
Studentsdataframe.T

,0,1,2,3,4,5,6,7,8,9
S.No,1,2,3,4,5,6,7,8,9,10
Student Name,Annie,Amy,Ali,Daniel,Donald,Dinesh,Jacob,Julie,Sandhya,Salim
Roll No.,100231,100232,100233,100234,100235,100236,100237,100238,100239,100240
Total Marks,60,65,70,56,45,85,75,85,60,70

### Attributes-data types()

In [67]:
# data types of the data frame
Studentsdataframe.dtypes

S.No             int64
Student Name    object
Roll No.         int64
Total Marks      int64
dtype: object

### Attributes-ndim()

In [68]:
# ndim of the data frame
Studentsdataframe.ndim

2

### Attributes-shape()

In [69]:
# shape of the data frame
Studentsdataframe.shape

(10, 4)

**<p style="font-family: Arial; font-size:1.4em;color:blue;">Exercise: Attributes in the Dataframe </p>**

In [70]:
## In the above kids dataset check these attributes:
# head(), tail(), shape, dimension, data type

In [71]:
KidsData = pd.read_csv('Datasets/KidsData.csv')
KidsData

   Kids No.     Name Bag Color Items in Bag
0         1    Alice       Red         Book
1         2      Bob      Blue       Pencil
2         3  Charlie     Green        Ruler
3         4    Diana    Yellow       Eraser
4         5      Eve      Pink       Crayon
5         6    Frank    Orange     Notebook
6         7    Grace    Purple          Pen
7         8     Hank     White     Scissors
8         9      Ivy     Black         Glue
9        10     Jack     Brown       Marker

## DataFrame Indexing

In [72]:
# indexing data frame
Studentsdataframe=pd.read_csv("Datasets/Students Marks.csv",index_col ="Student Name")
# retrieving columns by indexing operator
first = Studentsdataframe[["Roll No."]]
first

              Roll No.
Student Name
Annie           100231
Amy             100232
Ali             100233
Daniel          100234
Donald          100235
Dinesh          100236
Jacob           100237
Julie           100238
Sandhya         100239
Salim           100240

**<p style="font-family: Arial; font-size:1.4em;color:blue;">Exercise: DataFrame Indexing </p>**

In [74]:
## From the kids dataset retrieve the column with name items in the bag with respect to the Kids No.

In [75]:
print(KidsData.head())
print(KidsData.tail())
print(KidsData.shape)
print(KidsData.ndim)
print(KidsData.dtypes)

   Kids No.     Name Bag Color Items in Bag
0         1    Alice       Red         Book
1         2      Bob      Blue       Pencil
2         3  Charlie     Green        Ruler
3         4    Diana    Yellow       Eraser
4         5      Eve      Pink       Crayon
   Kids No.   Name Bag Color Items in Bag
5         6  Frank    Orange     Notebook
6         7  Grace    Purple          Pen
7         8   Hank     White     Scissors
8         9    Ivy     Black         Glue
9        10   Jack     Brown       Marker
(10, 4)
2
Kids No.         int64
Name            object
Bag Color       object
Items in Bag    object
dtype: object

## Checking missing Values

In [76]:
# Missing Value
# let us create a data frame
import numpy as np
dict = {'First Score':[100, 90, np.nan, 95],
        'Second Score': [30, 45, 56, np.nan],
        'Third Score':[np.nan, 40, 80, 98]}
# creating a dataframe using dictionary
df = pd.DataFrame(dict)
df

   First Score  Second Score  Third Score
0        100.0          30.0          NaN
1         90.0          45.0         40.0
2          NaN          56.0         80.0
3         95.0           NaN         98.0

In [77]:
# using isnull function for the above data frame created
df.isnull()

   First Score  Second Score  Third Score
0        False         False         True
1        False         False        False
2         True         False        False
3        False          True        False

In [78]:
# using notnull function for the above data frame created
df.notnull()

   First Score  Second Score  Third Score
0         True          True        False
1         True          True         True
2        False          True         True
3         True         False         True

In [79]:
# using fillna() method to replace null values
df.fillna(0)

   First Score  Second Score  Third Score
0        100.0          30.0          0.0
1         90.0          45.0         40.0
2          0.0          56.0         80.0
3         95.0           0.0         98.0

**<p style="font-family: Arial; font-size:1.4em;color:blue;">Exercise: Check for Missing Value </p>**

In [80]:
## Check if there are any missing values in the kids dataset

In [81]:
KidsData = pd.read_csv('Datasets/KidsData.csv', index_col='Kids No.')
KidsData[['Items in Bag']]

         Items in Bag
Kids No.
1                Book
2              Pencil
3               Ruler
4              Eraser
5              Crayon
6            Notebook
7                 Pen
8            Scissors
9                Glue
10             Marker

In [82]:
# Adding a new column to the data frame
# create a new data frame
df = pd.DataFrame({'price': [3, 89, 45, 6], 'amount': [57, 42, 70, 43]})
df

   price  amount
0      3      57
1     89      42
2     45      70
3      6      43

In [83]:
# add a new column with total
df['total'] = [171, 3738, 3150, 258]
df

   price  amount  total
0      3      57    171
1     89      42   3738
2     45      70   3150
3      6      43    258

In [84]:
# drop a column
df.drop('total', axis=1, inplace=True)
df

   price  amount
0      3      57
1     89      42
2     45      70
3      6      43

In [85]:
# rename a column
df.rename(columns={'amount': 'quantity'}, inplace=True)
df

   price  quantity
0      3        57
1     89        42
2     45        70
3      6        43

**<p style="font-family: Arial; font-size:1.4em;color:blue;">Exercise: Column Manipulations </p>**

In [86]:
## Add a column to the KidsData dataframe with numbers from 2 to 11 named as count of kids

In [87]:

KidsData.isnull()

           Name  Bag Color  Items in Bag
Kids No.
1         False      False         False
2         False      False         False
3         False      False         False
4         False      False         False
5         False      False         False
6         False      False         False
7         False      False         False
8         False      False         False
9         False      False         False
10        False      False         False

In [88]:
KidsData['count of kids'] = range(2, 12)
KidsData

             Name Bag Color Items in Bag  count of kids
Kids No.
1           Alice       Red         Book              2
2             Bob      Blue       Pencil              3
3         Charlie     Green        Ruler              4
4           Diana    Yellow       Eraser              5
5             Eve      Pink       Crayon              6
6           Frank    Orange     Notebook              7
7           Grace    Purple          Pen              8
8            Hank     White     Scissors              9
9             Ivy     Black         Glue             10
10           Jack     Brown       Marker             11